import { writeFileSync } from 'node:fs';
import { DISHES } from '../src/data/dishes';
import { ARTICLES } from '../src/data/news';
import { BRANCHES } from '../src/data/branches';

const value = (input: unknown): string => {
  if (input == null) return 'NULL';
  if (typeof input === 'boolean') return String(input);
  if (typeof input === 'number') {
    if (!Number.isFinite(input)) throw new Error('Invalid numeric seed value');
    return String(input);
  }
  const text = typeof input === 'string' ? input : JSON.stringify(input);
  return "'" + text.replaceAll("'", "''") + "'";
};
function insert(table: string, records: Record<string, unknown>[]) {
  const columns = Object.keys(records[0]);
  return `INSERT INTO public.${table} (${columns.join(', ')}) VALUES\n` +
    records.map((record) => '(' + columns.map((key) => value(record[key])).join(', ') + ')').join(',\n') +
    '\nON CONFLICT (id) DO NOTHING;\n';
}
const sql = '-- Generated by bun run seed:generate. Catalog only: no customer data or credentials.\nBEGIN;\n\n' +
  insert('branches', BRANCHES.map((branch) => ({
    id: branch.id, code: branch.code, name: branch.name, address: branch.address,
    district: branch.district, phone: branch.phone, opening_hours: branch.openingHours,
    morning_slot: branch.morningSlot, afternoon_slot: branch.afternoonSlot,
    map_embed_url: branch.mapEmbedUrl, google_maps_link: branch.googleMapsLink,
    highlight: branch.highlight, is_original: branch.isOriginal || false,
  }))) + '\n' + insert('dishes', DISHES.map((dish) => ({
    id: dish.id, category: dish.category, name: dish.name, price: dish.price,
    formatted_price: dish.formattedPrice, image: dish.image,
    short_description: dish.shortDescription, full_description: dish.fullDescription,
    ingredients: dish.ingredients, is_signature: dish.isSignature || false,
    is_featured: dish.isFeatured || false, is_available: true,
    preparation_note: dish.preparationNote || null,
  }))) + '\n' + insert('articles', ARTICLES.map((article) => ({
    id: article.id, title: article.title, excerpt: article.excerpt, content: article.content,
    date: article.date, read_time: article.readTime, category: article.category,
    image: article.image, author: article.author, is_hero_article: article.isHeroArticle || false,
  }))) + '\nCOMMIT;\n';
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql);
console.log(`Seed generated: ${DISHES.length} dishes, ${ARTICLES.length} articles, ${BRANCHES.length} branches.`);
